#!/bin/sh
# Get repository root
REPO_ROOT=$(git rev-parse --show-toplevel)

# Update CHANGELOG.md using conventional-changelog
npm i --no-save conventional-changelog-cli
npx conventional-changelog -p angular -i $REPO_ROOT/CHANGELOG.md -s

# Commit changes
git add $REPO_ROOT/CHANGELOG.md
git commit -m "docs(changelog): update changelog #4"
