name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Create release
        uses: ffurrer2/simple-release-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-npm: true  # this prevents publishing to npm
          working-directory: ./demo
          commit-message: 'chore: release v{{version}}'  # custom commit message
          # Optional configuration (adjust as needed):
          # release-branches: 'main'  # default is 'main,master'
          # version-file: 'package.json'  # default is package.json
          # version-path: 'version'  # if version is not at root of package.json
          # tag-prefix: 'v'  # default is 'v' (creates tags like v1.0.0)
          # changelog-path: 'CHANGELOG.md'  # default is CHANGELOG.md
