name: Release Please

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Tags/commits
      pull-requests: write
      issues: write        # Labels
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          manifest-file: ".release-please-manifest.json"
          package-name: "demo"
  npm-publish:
    needs: release-please
    runs-on: ubuntu-latest
    if: github.event_name == 'release'  # Only run on release events
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci  # Clean install for production
      
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Required npm auth token